<?php

class CSSEditor {
    private $CSSHandle;

    public function __construct() {
        $this -> Init();
    }

    private function Init() {

        if(!file_exists('../../css/generate/')) {
           mkdir('../../css/generate/', 0777, true);
        }

        $this -> CSSHandle = fopen('../../css/generate/style.css', 'a+');

        if(!preg_match_all('/\/\*Generated by CSSEditor class\*\//', fgets($this -> CSSHandle))) {
            fwrite($this -> CSSHandle, '/*Generated by CSSEditor class*/');
        }
    }

    public function AddStyleGroup(string $selector, array $properties) {
        $cssItem = $selector.'{';
        
        foreach($properties as $propertie => $value) {
            $cssItem .= "$propertie: $value;";
        }

        $cssItem .= '}';

        fwrite($this -> CSSHandle, $cssItem);
    }
}